services:
  backend:
    build: ./backend
    container_name: hosting-provider-backend
    env_file:
      - ./backend/.env
      - .env
    environment:
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: hosting-provider-db
      DB_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend/tests:/app/tests
    networks:
      - hosting-provider-network

  db:
    image: postgres:17
    container_name: hosting-provider-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - hosting-provider-network

volumes:
  db-data:


networks:
  hosting-provider-network:
    driver: bridge
