services:
  db:
    image: postgres:17.1
    container_name: server_rental_db
    restart: always
    environment:
      POSTGRES_DB: "server_rental"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "12345"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      
volumes:
  db-data: